"use client";

import {
    useState,
} from "react";

import {
    Button,
} from "@/components/ui/button";

import {
    Container,
} from "@/components/layout/Container";

import {
    Divider,
} from "@/components/layout/Divider";

import {
    Grid,
} from "@/components/layout/Grid";

import {
    Inline,
} from "@/components/layout/Inline";

import {
    Page,
} from "@/components/layout/Page";

import {
    PageHeader,
} from "@/components/layout/PageHeader";

import {
    Section,
} from "@/components/layout/Section";

import {
    Stack,
} from "@/components/layout/Stack";

import {
    NotificationsOverview,
} from "@/components/dashboard/developers/notifications/NotificationsOverview";

import {
    NotificationsDeliveryChart,
} from "@/components/dashboard/developers/notifications/NotificationsDeliveryChart";

import {
    NotificationsChannelSummary,
} from "@/components/dashboard/developers/notifications/NotificationsChannelSummary";

import {
    NotificationsToolbar,
} from "@/components/dashboard/developers/notifications/NotificationsToolbar";

import {
    NotificationsTable,
} from "@/components/dashboard/developers/notifications/NotificationsTable";

import {
    NotificationsPagination,
} from "@/components/dashboard/developers/notifications/NotificationsPagination";

import {
    CreateNotificationDialog,
} from "@/components/dashboard/developers/notifications/CreateNotificationDialog";

export default function NotificationsPage() {
    const [
        createDialogOpen,
        setCreateDialogOpen,
    ] = useState(false);

    return (
        <Page>

            <Container className="py-8 lg:py-10">

                <Stack gap={8}>

                    {/* HEADER */}

                    <PageHeader
                        eyebrow="Notifications"
                        title="Notifications"
                        description="Configure and monitor the notifications generated by your merchant billing infrastructure."
                        actions={
                            <Inline gap={2}>

                                <Button variant="outline">
                                    Notification settings
                                </Button>

                                <Button
                                    onClick={() =>
                                        setCreateDialogOpen(
                                            true,
                                        )
                                    }
                                >
                                    Create notification
                                </Button>

                            </Inline>
                        }
                    />

                    <Divider />

                    {/* OVERVIEW */}

                    <NotificationsOverview />

                    {/* PERFORMANCE */}

                    <Section
                        title="Notification performance"
                        description="Monitor notification delivery across the channels configured for your merchant."
                    >

                        <Grid className="grid-cols-1 gap-4 xl:grid-cols-3">

                            <NotificationsDeliveryChart />

                            <NotificationsChannelSummary />

                        </Grid>

                    </Section>

                    {/* MANAGEMENT */}

                    <Section
                        title="Notification policies"
                        description="Search, filter, and manage the rules that generate notifications."
                    >

                        <Stack gap={4}>

                            <NotificationsToolbar />

                            <NotificationsTable />

                            <NotificationsPagination />

                        </Stack>

                    </Section>

                </Stack>

            </Container>

            <CreateNotificationDialog
                open={createDialogOpen}
                onOpenChange={
                    setCreateDialogOpen
                }
            />

        </Page>
    );
}