"use client";

import {
    useState,
} from "react";

import {
    Button,
} from "@/components/ui/button";

import {
    Container,
} from "@/components/layout/Container";

import {
    Divider,
} from "@/components/layout/Divider";

import {
    Inline,
} from "@/components/layout/Inline";

import {
    Page,
} from "@/components/layout/Page";

import {
    PageHeader,
} from "@/components/layout/PageHeader";

import {
    Section,
} from "@/components/layout/Section";

import {
    Stack,
} from "@/components/layout/Stack";

import {
    NotificationsOverview,
} from "@/components/dashboard/developers/notifications/NotificationsOverview";

import {
    NotificationsDeliveryChart,
} from "@/components/dashboard/developers/notifications/NotificationsDeliveryChart";

import {
    NotificationsChannelSummary,
} from "@/components/dashboard/developers/notifications/NotificationsChannelSummary";

import {
    NotificationsToolbar,
} from "@/components/dashboard/developers/notifications/NotificationsToolbar";

import {
    NotificationsTable,
} from "@/components/dashboard/developers/notifications/NotificationsTable";

import {
    NotificationsPagination,
} from "@/components/dashboard/developers/notifications/NotificationsPagination";

import {
    CreateNotificationDialog,
} from "@/components/dashboard/developers/notifications/CreateNotificationDialog";

import {
    useMerchantNotificationsPage,
} from "@/hooks/pages/merchant/useMerchantNotificationsPage";

export default function NotificationsPage() {
    const page =
        useMerchantNotificationsPage();

    const [
        createDialogOpen,
        setCreateDialogOpen,
    ] =
        useState(false);

    if (
        page.status ===
        "waiting" ||
        page.status ===
        "loading"
    ) {
        return (
            <Page>
                <Container className="py-8 lg:py-10">
                    <div className="rounded-xl border bg-card p-8">
                        <p className="text-sm text-muted-foreground">
                            Loading notification data...
                        </p>
                    </div>
                </Container>
            </Page>
        );
    }

    if (
        page.status ===
        "error"
    ) {
        return (
            <Page>
                <Container className="py-8 lg:py-10">
                    <div className="rounded-xl border bg-card p-8">
                        <p className="text-sm font-medium">
                            Unable to load notifications
                        </p>

                        <p className="mt-2 text-sm text-muted-foreground">
                            {page.error?.message ??
                                "An unexpected error occurred."}
                        </p>

                        <Button
                            className="mt-4"
                            variant="outline"
                            onClick={() => {
                                void page.actions.refresh.run();
                            }}
                        >
                            Retry
                        </Button>
                    </div>
                </Container>
            </Page>
        );
    }

    if (
        page.status ===
        "unavailable"
    ) {
        return (
            <Page>
                <Container className="py-8 lg:py-10">
                    <Stack gap={8}>
                        <PageHeader
                            eyebrow="Developers"
                            title="Notifications"
                            description="Configure and monitor notification policies generated by your merchant billing infrastructure."
                        />

                        <Divider />

                        <div className="rounded-xl border bg-card p-8">
                            <p className="text-sm font-medium">
                                Notification API not yet available
                            </p>

                            <p className="mt-2 max-w-2xl text-sm text-muted-foreground">
                                The notification resource has been prepared at the UI and hook layers, but the corresponding merchant SDK operation has not yet been implemented.
                            </p>

                            <div className="mt-4 flex items-center gap-2">
                                <Button
                                    variant="outline"
                                    onClick={() => {
                                        void page.actions.refresh.run();
                                    }}
                                >
                                    Refresh
                                </Button>

                                <span className="text-xs text-muted-foreground">
                                    Live mode
                                </span>
                            </div>
                        </div>
                    </Stack>
                </Container>
            </Page>
        );
    }

    return (
        <Page>
            <Container className="py-8 lg:py-10">
                <Stack gap={8}>
                    <PageHeader
                        eyebrow="Developers"
                        title="Notifications"
                        description="Configure and monitor the notifications generated by your merchant billing infrastructure."
                        actions={
                            <Inline gap={2}>
                                <Button
                                    variant="outline"
                                >
                                    Notification settings
                                </Button>

                                <Button
                                    onClick={() =>
                                        setCreateDialogOpen(
                                            true,
                                        )
                                    }
                                >
                                    Create notification
                                </Button>
                            </Inline>
                        }
                    />

                    <Divider />

                    <NotificationsOverview
                        total={
                            page.summary
                                .total
                        }
                        active={
                            page.summary
                                .active
                        }
                        sent={
                            page.summary
                                .sent
                        }
                        successRate={
                            page.summary
                                .successRate
                        }
                        needsAttention={
                            page.summary
                                .needsAttention
                        }
                    />

                    <Section
                        title="Notification performance"
                        description="Monitor notification delivery across the channels configured for your merchant."
                    >
                        <div className="grid grid-cols-1 gap-4 xl:grid-cols-3">
                            <NotificationsDeliveryChart
                                successRate={
                                    page.summary
                                        .successRate
                                }
                            />

                            <NotificationsChannelSummary
                                notifications={
                                    page.notifications
                                }
                            />
                        </div>
                    </Section>

                    <Section
                        title="Notification policies"
                        description="Search, filter, and manage the rules that generate notifications."
                    >
                        <Stack gap={4}>
                            <NotificationsToolbar
                                search={
                                    page.table
                                        .search
                                }
                                onSearchChange={
                                    page.table
                                        .setSearch
                                }
                                status={
                                    page.table
                                        .status
                                }
                                channel={
                                    page.table
                                        .channel
                                }
                                onStatusChange={
                                    page.table
                                        .setStatus
                                }
                                onChannelChange={
                                    page.table
                                        .setChannel
                                }
                                onRefresh={
                                    page.actions
                                        .refresh
                                        .run
                                }
                                refreshing={
                                    page.actions
                                        .refresh
                                        .loading
                                }
                                refreshAvailable={
                                    page.actions
                                        .refresh
                                        .available
                                }
                            />

                            <NotificationsTable
                                notifications={
                                    page.filteredNotifications
                                }
                            />

                            <NotificationsPagination
                                visible={
                                    page
                                        .filteredNotifications
                                        .length
                                }
                                total={
                                    page
                                        .notifications
                                        .length
                                }
                            />
                        </Stack>
                    </Section>

                    {page.actions
                        .refresh
                        .loading && (
                        <p className="text-xs text-muted-foreground">
                            Refreshing notification data...
                        </p>
                    )}
                </Stack>
            </Container>

            <CreateNotificationDialog
                open={
                    createDialogOpen
                }
                onOpenChange={
                    setCreateDialogOpen
                }
                createAvailable={
                    false
                }
            />
        </Page>
    );
}